# See the documentation for more information:
# https://packit.dev/docs/configuration/

specfile_path: tmt-plugin-diana.spec

# add or remove files that should be synced
files_to_sync:
    - tmt-plugin-diana.spec
    - .packit.yaml

# name in upstream package repository or registry (e.g. in PyPI)
upstream_package_name: tmt-plugin-diana
# downstream (Fedora) RPM package name
downstream_package_name: tmt-plugin-diana

jobs:
  - job: copr_build
    owner: conscript89
    project: tmt-plugin-diana
    trigger: commit
    targets:
      - fedora-stable
